# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

# Original author: Cho (https://github.com/pagecho/maupassant)
# Adapted for Hugo by: JokerQyou (https://github.com/JokerQyou/maupassant-hugo)
# Forked and improved by Flysnow-org (https://github.com/flysnow-org/maupassant-hugo)
# Forked, "Maupassant World Hugo" is an internatioanalized and improved version by bryndin (https://github.com/bryndin/maupassant-hugo)

name = "Maupassant World Hugo"
license = "MIT"
licenselink = "https://github.com/bryndin/maupassant-hugo/blob/master/LICENSE.md"
description = "Internationalized version of Maupassant Theme. The template was originally designed by Cho (pagecho)."
homepage = "https://github.com/bryndin/maupassant-hugo"
tags = ["blog", "simple", "responsive", "minimal", "personal", "light", "multilingual"]
features = ["Search"]
min_version = "0.110.0"

# If the theme has multiple authors
authors = [
  {name = "bryndin", homepage = "https://github.com/bryndin/maupassant-hugo"},
  {name = "flysnow-org", homepage = "https://github.com/flysnow-org/maupassant-hugo"},
  {name = "JokerQyou", homepage = "https://github.com/JokerQyou/maupassant-hugo"}
]

[originauthor]
  name = "Joker Qyou"
  homepage = "https://mynook.info"


# If porting an existing theme
[original]
    author = "pagecho"
    homepage = "https://github.com/pagecho"
    repo = "https://github.com/pagecho/maupassant"