##### Default parameters #####################################################

# (required) The base URL of your site. This will be prepended to all relative URLs
baseURL = 'https://www.flysnow.org'
 # (required) Website title
title = '飞雪无情的博客'
# Theme name
theme = 'maupassant'

# project's default language
defaultContentLanguage = 'en'
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# timeZone = "America/New_York"
# post excerpt, content summary length for post list
summaryLength = 140   # see https://gohugo.io/content-management/excerpts/
hasCJKLanguage = true #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

##### Services ###############################################################

[services]
[services.googleAnalytics]
  ID = '' # Google Analytics ID. See https://gohugo.io/templates/internal/#configure-google-analytics

[services.disqus]
  shortname = '' # Disqus comments. See https://gohugo.io/templates/embedded/?search-input=disqusShortname#configure-disqus

##### Site Params ############################################################

[params]
  author = "飞雪无情"
  subtitle = "专注于Android、Java、Go语言(golang)、移动互联网、项目管理、软件架构"
  keywords = "golang,go语言,go语言笔记,飞雪无情,java,android,博客,项目管理,python,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等"
  busuanzi = true # https://github.com/soxft/busuanzi website statistics analyzer
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx

  # Here you can put list of custom JS/CSS files you want to be loaded
  customCSS = []
  customJS = []

  # Global table of contents switch. For non-blog posts pages, consider turning it off in `front matter`
  toc = true

##### Side Column Widgets ####################################################

### Site Search Widget
[params.search]
  disable = false # Disables and hides the widget
  localSearch = true # Use local search (true), or Google Search over your domain (false)

### Latest Posts Widget
[params.wLatestPosts]
  disable = false # Disables and hides the widget
  limit = 5 # Maximum number of posts to show
  type = "post" # Only show latest posts of this type. See https://gohugo.io/methods/page/type/

### Ads Widget.  Removing all entries disables the widget.
# If `img` is not specified, the text in `title` will be used instead
[[params.wAds]]
  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
  title = "【2019双12】ALL IN CLoud 低至1折"
  url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
[[params.wAds]]
  img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
  title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
  url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
[[params.wAds]]
  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"
  title = "【渠道专享低折扣】11月特惠 限时2折"
  url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"

### Categories Widget
[params.wCategories]
  disable = false # Disables and hides the widget
  
### Tags Widget
[params.wTags]
  disable = false # Disables and hides the widget

### Links Widget.  Removing all entries disables the widget.
[[params.wLinks]]
  name = "飞雪无情的博客"
  title = "飞雪无情的博客"
  url = "https://www.flysnow.org/"

[[params.wLinks]]
  name = "Android Gradle权威指南"
  title = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"

### Meta Widget

##### Page Features ##########################################################

### Related Posts.  At the bottom of the post page, show links to related posts.
# See https://gohugo.io/content-management/related/
[params.relatedPosts]
  disable = false # Disables and hides the widget
  limit = 5 # Max number of entries to display
  type = "post" # Only show entries from this type. See https://gohugo.io/methods/page/type/

### Copyright statement for posts
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"


##### Alternative comments services ##########################################

## utteranc, see https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "your github repo" # Change to your repository
  issueTerm = "pathname"
  theme = "github-light"

## waline, see https://waline.js.org/
[params.waline]
  enable = false
  placeholder = ""  # Default text of comment box
  serverURL = "Your waline serverURL" # Change to your serverURL

##### Markup settings ########################################################

[markup]
  [markup.highlight]
    style = "github"

##### Menu ###################################################################

# See https://gohugo.io/content-management/menus/#define-in-site-configuration
[menus]
  [[menu.main]]
    identifier = "tools"
    name = "工具"
    pageRef = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "menu_Archives"  # i18n key, see files in `i18n` folder
    pageRef = "/archives/"  # keep the trainling slashes
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "menu_About" # i18n key, see files in `i18n` folder
    pageRef = "/about/" # keep the trainling slashes
    weight = 4
