##### Default parameters #####################################################

# (required) The base URL of your site. This will be prepended to all relative URLs
baseURL = 'https://www.flysnow.org'
 # (required) Website title
title = '飞雪无情的博客'
# Theme name
theme = 'maupassant'

# project's default language
defaultContentLanguage = 'en'
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# timeZone = "America/New_York"
# post excerpt, content summary length for post list
summaryLength = 140   # see https://gohugo.io/content-management/excerpts/
hasCJKLanguage = true #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

##### Services ###############################################################

[services]
[services.googleAnalytics]
  ID = '' # Google Analytics ID. See https://gohugo.io/templates/internal/#configure-google-analytics

[services.disqus]
  shortname = '' # Disqus comments. See https://gohugo.io/templates/embedded/?search-input=disqusShortname#configure-disqus

##### Site Params ############################################################

[params]
  author = "飞雪无情"
  subtitle = "专注于Android、Java、Go语言(golang)、移动互联网、项目管理、软件架构"
  keywords = "golang,go语言,go语言笔记,飞雪无情,java,android,博客,项目管理,python,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = []
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "飞雪无情的博客"
  name = "飞雪无情的博客"
  url = "https://www.flysnow.org/"

[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"

## 侧边栏广告位
[[params.ads]]
  title = "【2019双12】ALL IN CLoud 低至1折"
  url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
[[params.ads]]
  title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
  url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
  img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
[[params.ads]]
  title = "【渠道专享低折扣】11月特惠 限时2折"
  url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## utteranc, see https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "your github repo" # Change to your repository
  issueTerm = "pathname"
  theme = "github-light"
## waline, see https://waline.js.org/
[params.waline]
  enable = false
  placeholder = ""  # Default text of comment box
  serverURL = "Your waline serverURL" # Change to your serverURL
## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

##### Markup settings ########################################################

[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

##### Menu ###################################################################

# See https://gohugo.io/content-management/menus/#define-in-site-configuration
[menus]
  [[menu.main]]
    identifier = "tools"
    name = "工具"
    pageRef = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "menu_Archives"  # i18n key, see files in `i18n` folder
    pageRef = "/archives/"  # keep the trainling slashes
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "menu_About" # i18n key, see files in `i18n` folder
    pageRef = "/about/" # keep the trainling slashes
    weight = 4
