##### Global parameters #####################################################

# (required) The base URL of your site. This will be prepended to all relative URLs
baseURL = 'https://github.com/bryndin/maupassant-hugo/'
# (required) Website title
title = "Maupassant: A Hugo Blog Theme"
# Theme name
theme = 'maupassant'

# Project's default language
defaultContentLanguage = 'en'
# Language code to declare in HTML metadata
languageCode = "en-us"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/Los_Angeles"
# Post excerpt, content summary length for post list
summaryLength = 140   # see https://gohugo.io/content-management/excerpts/

# Auto-detect Chinese/Japanese/Korean Languages in the content, for word counts and summaries to work correctly.
hasCJKLanguage = true # see: https://gohugo.io/getting-started/configuration/#hascjklanguage

##### Site Specific Params ###################################################

[params]
  # (required) Directory name of your blog content (typically is `posts`)
  # To mark any page outside of that directy as a blog post, set e.g. `type: posts` in front matter
  blogType = "posts"

  author = "bryndin"
  subtitle = "Elegant & simple blog theme inspired by Guy de Maupassant"
  keywords = "maupassant, hugo, theme, free, open-source, blog, blogger, light, website, simple, minimal, responsive, SEO friendly, fast, demo, demosight, i18n, en, ja, ko, zh"
  description = "Maupassant is a free and open-source Hugo theme designed for bloggers. It features a clean, minimal aesthetic inspired by the works of Guy de Maupassant, perfect for showcasing your writing."

  # Here you can put list of custom JS/CSS files you want to be loaded
  customCSS = []
  customJS = []

  # Global table of contents switch. For non-blog posts pages, consider turning it off in `front matter`
  # ToC is currently broken, keep it off for now
  toc = false

# Google Tag Manager (GTM)
[params.googletagmanager]
  gtmid = "" # Google Tag Manager ID

#---- Side Column Widgets ----------------------------------------------------

### Site Search Widget
[params.search]
  disable = false # Disables and hides the widget
  localSearch = true # Use local search (true), or Google Search over your domain (false)

### Latest Posts Widget
[params.wLatestPosts]
  disable = false # Disables and hides the widget
  limit = 5 # Max number of entries to show
  type = "posts" # Only show entries from this type. See https://gohugo.io/methods/page/type/

### Ads Widget.  Removing all entries disables the widget.
# If `img` is not specified, the text in `title` will be used instead
[[params.wAds]]
  img = "https://gohugo.io/images/hugo-logo-wide.svg"
  title = "Hugo, framework for building websites"
  url = "https://gohugo.io/"

### Categories Widget
[params.wCategories]
  disable = false # Disables and hides the widget
  
### Tags Widget
[params.wTags]
  disable = false # Disables and hides the widget

### Links Widget.  Removing all entries disables the widget.
[[params.wLinks]]
  name = "Get Maupassant Theme"
  title = "Download Maupassant Theme on GitHub"
  url = "https://github.com/bryndin/maupassant-hugo/"

[[params.wLinks]]
  name = "Visit my GitHub"
  title = "My GitHub"
  url = "https://github.com/bryndin"

[[params.wLinks]]
  name = "Learn Hugo"
  title = "Hugo"
  url = "https://gohugo.io/"

### Socials Widget
[params.wSocials]
  disable = false # Disables and hides the widget

#---- Page Features ----------------------------------------------------------

### Related Posts.  At the bottom of the post page, show links to related posts.
# See https://gohugo.io/content-management/related/
[params.relatedPosts]
  disable = false # Disables and hides the widget
  limit = 5 # Max number of entries to show
  type = "posts" # Only show entries from this type. See https://gohugo.io/methods/page/type/

#---- Alternative comments services ------------------------------------------

# Hugo natively supports Disqus (configured below), but we have other options as well

## utteranc, see https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "your github repo" # Change to your repository
  issueTerm = "pathname"
  theme = "github-light"

## waline, see https://waline.js.org/
[params.waline]
  enable = false
  placeholder = ""  # Default text of comment box
  serverURL = "Your waline serverURL" # Change to your serverURL

##### Services ###############################################################

[services]
  # Enable comments via Disqus
  [services.disqus]
    shortname = '' # see https://gohugo.io/templates/embedded/?search-input=disqusShortname#configure-disqus

##### Main Menu ##############################################################

# See https://gohugo.io/content-management/menus/#define-in-site-configuration
[menus]
  [[menu.main]]
    identifier = "archives"
    name = "menu_Archives"  # i18n key, see files in `i18n` folder
    pageRef = "/archives/"  # keep the trainling slashes
    weight = 3              # sorting order

  [[menu.main]]
    identifier = "about"
    name = "menu_About"     # i18n key, see files in `i18n` folder
    pageRef = "/about/"     # keep the trainling slashes
    weight = 4              # sorting order

##### Markup settings ########################################################

# see https://gohugo.io/getting-started/configuration-markup/
[markup]
  # Code Block Highlighting, see https://gohugo.io/getting-started/configuration-markup/#highlight
  [markup.highlight]
    style = "github"
